install:
	cp -v filetype_extensions.conf ~/.config/geany/filetype_extensions.conf
	cp -v filedefs/filetypes.Arduino.conf ~/.config/geany/filedefs/filetypes.Arduino.conf
	cp -v templates/files/sketch.ino ~/.config/geany/templates/files/sketch.ino
